import io
from typing import Dict, Any, List
from backend.utils.config import logger

# Import docx library, provide mock/error boundaries if not installed
try:
    import docx
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    HAS_DOCX = True
except ImportError:
    logger.warning("python-docx is not installed. Word document downloads will be unavailable.")
    HAS_DOCX = False

def generate_biomedical_docx(report_data: Dict[str, Any]) -> bytes:
    """Generates a professional Word (DOCX) report from consensus report data."""
    if not HAS_DOCX:
        logger.error("DOCX generation requested but python-docx is missing.")
        raise ImportError("python-docx is not installed in the workspace.")

    logger.info("Initializing DOCX generation.")
    
    doc = docx.Document()
    
    # Page setup
    sections = doc.sections
    for section in sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

    # Styles
    style_normal = doc.styles['Normal']
    font = style_normal.font
    font.name = 'Arial'
    font.size = Pt(10.5)
    font.color.rgb = RGBColor(0x2D, 0x37, 0x48) # Charcoal

    # Document Header
    p_title = doc.add_paragraph()
    p_title_run = p_title.add_run("BioReason-X Biomedical Intelligence Report")
    p_title_run.bold = True
    p_title_run.font.size = Pt(20)
    p_title_run.font.color.rgb = RGBColor(0x1A, 0x36, 0x5D) # Deep Blue
    
    p_sub = doc.add_paragraph()
    p_sub_run = p_sub.add_run("Mutation → Mechanism → Therapy Intelligence Platform")
    p_sub_run.italic = True
    p_sub_run.font.size = Pt(11)
    p_sub_run.font.color.rgb = RGBColor(0x2B, 0x6C, 0xB0) # Slate Blue
    
    doc.add_paragraph("_" * 60) # Divider
    doc.add_paragraph()

    # Mutation Overview
    mutation_input = report_data.get("mutation_input", "Unknown Variant")
    consensus = report_data.get("consensus", {})
    confidence_score = consensus.get("confidence_score", "N/A")
    mutation_details = report_data.get("mutation_details", {})
    
    gene = mutation_details.get("gene", "N/A")
    mut_type = mutation_details.get("mutation_type", "N/A")
    clin_sig = mutation_details.get("clinical_significance", "N/A")

    # Add Table
    table = doc.add_table(rows=5, cols=2)
    table.style = 'Light Shading Accent 1'
    
    row_headers = [
        "Target Mutation", "Affected Gene", "Mutation Type", 
        "Clinical Significance", "Validation Confidence"
    ]
    row_values = [
        mutation_input, gene, mut_type, clin_sig, f"{confidence_score}%"
    ]
    
    for i in range(5):
        hdr_cell = table.cell(i, 0)
        val_cell = table.cell(i, 1)
        
        hdr_cell.text = row_headers[i]
        val_cell.text = row_values[i]
        
        # Style headers
        hdr_cell.paragraphs[0].runs[0].font.bold = True
        hdr_cell.paragraphs[0].runs[0].font.color.rgb = RGBColor(0x1A, 0x36, 0x5D)

    doc.add_paragraph() # Spacer

    # Executive Summary Section
    h_ex = doc.add_heading(level=1)
    h_ex_run = h_ex.add_run("Executive Summary")
    h_ex_run.font.color.rgb = RGBColor(0x1A, 0x36, 0x5D)
    summary_text = consensus.get("final_findings", "No final findings summary generated by the Consensus Agent.")
    doc.add_paragraph(summary_text)

    # Gene and Protein Impact Section
    h_gp = doc.add_heading(level=1)
    h_gp_run = h_gp.add_run("Gene & Protein Disruption")
    h_gp_run.font.color.rgb = RGBColor(0x1A, 0x36, 0x5D)
    protein_impact = report_data.get("protein_impact", "No protein impact details compiled.")
    doc.add_paragraph(protein_impact)

    # Pathway Cascade Section
    h_path = doc.add_heading(level=1)
    h_path_run = h_path.add_run("Pathway Cascade Impact")
    h_path_run.font.color.rgb = RGBColor(0x1A, 0x36, 0x5D)
    pathway_reasoning = report_data.get("pathway_reasoning", {})
    if isinstance(pathway_reasoning, dict):
        pathway_summary = pathway_reasoning.get("pathway_reasoning", "No pathway data provided.")
    else:
        pathway_summary = str(pathway_reasoning)
    doc.add_paragraph(pathway_summary)

    # Disease Association Section
    h_dis = doc.add_heading(level=1)
    h_dis_run = h_dis.add_run("Disease Associations")
    h_dis_run.font.color.rgb = RGBColor(0x1A, 0x36, 0x5D)
    disease_associations = consensus.get("disease_associations", [])
    if disease_associations:
        if isinstance(disease_associations, list):
            for disease in disease_associations:
                doc.add_paragraph(f"• {disease}", style='List Bullet')
        else:
            doc.add_paragraph(str(disease_associations))
    else:
        doc.add_paragraph("No direct disease associations cataloged.")

    # Therapy Recommendations Table
    doc.add_paragraph()
    h_tx = doc.add_heading(level=1)
    h_tx_run = h_tx.add_run("Therapy Recommendations")
    h_tx_run.font.color.rgb = RGBColor(0x1A, 0x36, 0x5D)
    
    therapies = report_data.get("therapies", [])
    if therapies:
        tx_table = doc.add_table(rows=1, cols=3)
        tx_table.style = 'Table Grid'
        
        hdr_cells = tx_table.rows[0].cells
        hdr_cells[0].text = "Therapy / Class"
        hdr_cells[1].text = "Rationale"
        hdr_cells[2].text = "Relevance"
        
        for cell in hdr_cells:
            cell.paragraphs[0].runs[0].font.bold = True
            cell.paragraphs[0].runs[0].font.color.rgb = RGBColor(0x1A, 0x36, 0x5D)
            
        for tx in therapies:
            row_cells = tx_table.add_row().cells
            row_cells[0].text = tx.get("drug", tx.get("therapy_name", "N/A"))
            row_cells[1].text = tx.get("rationale", "N/A")
            row_cells[2].text = tx.get("evidence_level", tx.get("relevance", "High"))
    else:
        doc.add_paragraph("No targeted therapies recommended.")

    # Literature Evidence Section
    doc.add_paragraph()
    h_lit = doc.add_heading(level=1)
    h_lit_run = h_lit.add_run("Supporting Evidence & Publications")
    h_lit_run.font.color.rgb = RGBColor(0x1A, 0x36, 0x5D)
    
    evidence = report_data.get("literature_evidence", [])
    if evidence:
        for ev in evidence:
            title = ev.get("title", "Unknown Publication")
            abstract = ev.get("abstract", "")
            source = ev.get("source", "Literature Database")
            doc_id = ev.get("id", "N/A")
            
            p_ev = doc.add_paragraph()
            p_ev_run = p_ev.add_run(f"{doc_id}: {title} ({source})\n")
            p_ev_run.bold = True
            
            p_ev_abs = p_ev.add_run(f"Abstract: {abstract}")
            p_ev_abs.italic = True
            p_ev_abs.font.size = Pt(9.5)
            p_ev_abs.font.color.rgb = RGBColor(0x4A, 0x55, 0x68)
    else:
        doc.add_paragraph("No indexed publications referenced.")

    # Final Clinical Recommendation Section
    doc.add_paragraph()
    h_rec = doc.add_heading(level=1)
    h_rec_run = h_rec.add_run("Consensus Final Recommendation")
    h_rec_run.font.color.rgb = RGBColor(0x1A, 0x36, 0x5D)
    final_rec = consensus.get("final_recommendation", "No clinical recommendations finalized.")
    doc.add_paragraph(final_rec)

    # Save to buffer
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    docx_bytes = buffer.getvalue()
    buffer.close()
    
    logger.info("DOCX generation completed.")
    return docx_bytes
